project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remote Sensing - Learning Diary"
  author: "Marta Woroniecka"
  date: "18-01-2024"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

